# Generated by Django 4.2.28 on 2026-02-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Land size in acres', max_digits=10)),
                ('crop_type', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Cotton', 'Cotton'), ('Soybean', 'Soybean'), ('Sugarcane', 'Sugarcane'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(help_text='Farm location/address', max_length=255)),
                ('annual_income', models.DecimalField(decimal_places=2, help_text='Annual income in USD', max_digits=12)),
                ('land_documents', models.FileField(blank=True, null=True, upload_to='farmer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
