# Generated by Django 4.2.28 on 2026-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, help_text='Annual income in BDT', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, help_text='Maximum loan amount in BDT', max_digits=12),
        ),
    ]
