# Generated by Django 6.0.3 on 2026-03-31 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_user_is_verified_alter_farmerprofile_annual_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_card',
            field=models.FileField(blank=True, help_text='Upload NID card (front and back)', null=True, upload_to='nid_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_verified',
            field=models.BooleanField(default=False, help_text='Whether NID has been verified by bank officer'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nid_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
