# Generated by Django 6.0.3 on 2026-03-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0008_user_nid_card_user_nid_verified_user_nid_verified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nid_card',
        ),
        migrations.AddField(
            model_name='user',
            name='nid_card_back',
            field=models.FileField(blank=True, help_text='Upload NID card back side', null=True, upload_to='nid_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_card_front',
            field=models.FileField(blank=True, help_text='Upload NID card front side', null=True, upload_to='nid_cards/'),
        ),
    ]
