# Generated by Django 6.0.3 on 2026-04-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0009_remove_user_nid_card_user_nid_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID number (unique per farmer)', max_length=20, null=True, unique=True),
        ),
    ]
