# Generated by Django 6.0.3 on 2026-04-05 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_user_nid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
