# Generated by Django 6.0.3 on 2026-04-05 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_alter_loanapplication_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
