# Generated by Django 6.0.3 on 2026-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0012_alter_loanapplication_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='For Bank Officers - requires admin approval'),
        ),
    ]
